---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: nightly


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Nightly: At 00:00 on Monday, Wednesday, and Friday
  schedule:
    - cron: '0 18 * * 1,3,5'

jobs:

  # (1/2) Determine repository params
  params:
    uses: ./.github/workflows/params.yml

  # (2/2) Build
  docker:
    needs: [params]
    uses: lapzeon/github-actions/.github/workflows/docker-name-version-flavour-arch.yml@main
    with:
      enabled: true
      can_deploy: true
      matrix: ${{ needs.params.outputs.matrix }}
      refs: ${{ needs.params.outputs.refs }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
